/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceWorkspaceIdRouteImport } from './routes/workspace.$workspaceId'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsProjectsProjectIdRouteImport } from './routes/settings.projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdRoute = WorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProjectsProjectIdRoute =
  SettingsProjectsProjectIdRouteImport.update({
    id: '/settings/projects/$projectId',
    path: '/settings/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
  '/settings/projects/$projectId': typeof SettingsProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
  '/settings/projects/$projectId': typeof SettingsProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
  '/settings/projects/$projectId': typeof SettingsProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings/general'
    | '/workspace/$workspaceId'
    | '/settings/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/general'
    | '/workspace/$workspaceId'
    | '/settings/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/settings/general'
    | '/workspace/$workspaceId'
    | '/settings/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  WorkspaceWorkspaceIdRoute: typeof WorkspaceWorkspaceIdRoute
  SettingsProjectsProjectIdRoute: typeof SettingsProjectsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId': {
      id: '/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/projects/$projectId': {
      id: '/settings/projects/$projectId'
      path: '/settings/projects/$projectId'
      fullPath: '/settings/projects/$projectId'
      preLoaderRoute: typeof SettingsProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  WorkspaceWorkspaceIdRoute: WorkspaceWorkspaceIdRoute,
  SettingsProjectsProjectIdRoute: SettingsProjectsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
